<a href="https://colab.research.google.com/github/rohandawar/pandaspractise/blob/main/Pandas_Practise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import numpy as np

In [22]:

# Create a dictionary with sample data
data = {
    'Order_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Product': ['Laptop', 'T-shirt', 'Book', 'Smartphone', 'Jeans', 'Headphones', 'Jacket', 'Tablet', 'Novel', 'Dress'],
    'Category': ['Electronics', 'Clothing', 'Books', 'Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Books', 'Clothing'],
    'Price': [800, 20, 15, 500, 40, 50, 60, 300, 10, 35],
    'Quantity': [2, 5, 3, 1, 2, 4, 1, 3, 6, 2],
    'Date': ['2023-08-01', '2023-08-02', '2023-08-02', '2023-08-03', '2023-08-03', '2023-08-04', '2023-08-04', '2023-08-05', '2023-08-05', '2023-08-06']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Print the DataFrame
df.head()

   Order_ID     Product     Category  Price  Quantity       Date
0         1      Laptop  Electronics    800         2 2023-08-01
1         2     T-shirt     Clothing     20         5 2023-08-02
2         3        Book        Books     15         3 2023-08-02
3         4  Smartphone  Electronics    500         1 2023-08-03
4         5       Jeans     Clothing     40         2 2023-08-03

In [23]:
# checking the shape
df.shape

(10, 6)

Coding Challenge:
Write a Python program that performs the following tasks using the provided sample dataset:

- Calculate the total sales (Price * Quantity) for each order.
- Calculate the total sales for each product category.
- Find the product with the highest total sales.
- Calculate the average price of products in each category.

In [24]:
#Calculate the total sales (Price * Quantity) for each order.
df['Total_Sales'] = df['Price'] * df['Quantity']
df.head()

   Order_ID     Product     Category  Price  Quantity       Date  Total_Sales
0         1      Laptop  Electronics    800         2 2023-08-01         1600
1         2     T-shirt     Clothing     20         5 2023-08-02          100
2         3        Book        Books     15         3 2023-08-02           45
3         4  Smartphone  Electronics    500         1 2023-08-03          500
4         5       Jeans     Clothing     40         2 2023-08-03           80

In [25]:
#Calculate the total sales for each product category.
df.groupby('Category').sum('Total_Sales').sort_values('Total_Sales', ascending=False)

             Order_ID  Price  Quantity  Total_Sales
Category
Electronics        19   1650        10         3200
Clothing           24    155        10          310
Books              12     25         9          105

In [50]:
#Find the product with the highest total sales.
# df.groupby('Product').sum('Total_Sales').sort_values('Total_Sales', ascending=False)
df.groupby(['Product'])['Total_Sales'].sum().sort_values(ascending=False)

Product
Laptop        1600
Tablet         900
Smartphone     500
Headphones     200
T-shirt        100
Jeans           80
Dress           70
Jacket          60
Novel           60
Book            45
Name: Total_Sales, dtype: int64

In [42]:
#Calculate the average price of products in each category.
df.groupby(['Category'])['Price'].agg(np.mean)

Category
Books           12.50
Clothing        38.75
Electronics    412.50
Name: Price, dtype: float64